//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AIRCRAFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_AIRCRAFT()
        {
            this.tb_FLIGHTS = new HashSet<tb_FLIGHTS>();
            this.tb_SEATS = new HashSet<tb_SEATS>();
        }
    
        public int AIRCRAFT_ID { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> CAPACITY { get; set; }
        public string MANUFACTURER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FLIGHTS> tb_FLIGHTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SEATS> tb_SEATS { get; set; }
    }
}
