//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AIRCRAFTSEATS
    {
        public int AIRCRAFTSEATSID { get; set; }
        public Nullable<int> AIRCRAFT_ID { get; set; }
        public Nullable<int> SEATS_ID { get; set; }
        public string SEAT_NUMBER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual tb_AIRCRAFT tb_AIRCRAFT { get; set; }
        public virtual tb_SEATS tb_SEATS { get; set; }
    }
}
