//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AIRPORTS
    {
        public int AIRPORT_ID { get; set; }
        public string AIPORT_NAME { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
    }
}
