//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BOOKINGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_BOOKINGS()
        {
            this.tb_CHECKINS = new HashSet<tb_CHECKINS>();
            this.tb_PAYMENTS = new HashSet<tb_PAYMENTS>();
        }
    
        public int BOOKING_ID { get; set; }
        public Nullable<int> FLIGHT_ID { get; set; }
        public Nullable<int> PASSENGER_ID { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
        public Nullable<int> SEAT_ID { get; set; }
        public string BOOKING_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHECKINS> tb_CHECKINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PAYMENTS> tb_PAYMENTS { get; set; }
        public virtual tb_FLIGHT_SCHEDULES tb_FLIGHT_SCHEDULES { get; set; }
        public virtual tb_PASSENGERS tb_PASSENGERS { get; set; }
        public virtual tb_SEATS tb_SEATS { get; set; }
    }
}
