//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHECKINS
    {
        public int CHECKIN_ID { get; set; }
        public Nullable<int> BOOKING_ID { get; set; }
        public Nullable<System.DateTime> CHECKIN_TIME { get; set; }
        public Nullable<decimal> BAGGAGE_COUNT { get; set; }
        public Nullable<int> SEAT_ID { get; set; }
        public string CHECKIN_STATUS { get; set; }
    
        public virtual tb_BOOKINGS tb_BOOKINGS { get; set; }
        public virtual tb_SEATS tb_SEATS { get; set; }
    }
}
