//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FLIGHT_SCHEDULES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_FLIGHT_SCHEDULES()
        {
            this.tb_BOOKINGS = new HashSet<tb_BOOKINGS>();
            this.tb_FLIGHT = new HashSet<tb_FLIGHT>();
        }
    
        public int FLIGHT_ID { get; set; }
        public Nullable<int> ORIGIN_AIRPORT_ID { get; set; }
        public Nullable<int> DESTINATION_AIRPORT_ID { get; set; }
        public string FLIGHT_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BOOKINGS> tb_BOOKINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FLIGHT> tb_FLIGHT { get; set; }
    }
}
