//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FLIGHT
    {
        public int ID_FLIGHT { get; set; }
        public Nullable<int> FLIGHT_ID { get; set; }
        public Nullable<int> AIRCRAFT_ID { get; set; }
        public Nullable<System.TimeSpan> DEPARTURE_TIME { get; set; }
        public Nullable<System.TimeSpan> ARRIVAL_TIME { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string FLIGHT_STATUS { get; set; }
    
        public virtual tb_AIRCRAFT tb_AIRCRAFT { get; set; }
        public virtual tb_FLIGHT_SCHEDULES tb_FLIGHT_SCHEDULES { get; set; }
    }
}
