//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PASSENGERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PASSENGERS()
        {
            this.tb_BOOKINGS = new HashSet<tb_BOOKINGS>();
        }
    
        public int PASSENGER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public string NATIONALITY { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BOOKINGS> tb_BOOKINGS { get; set; }
    }
}
