//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SEATS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SEATS()
        {
            this.tb_BOOKINGS = new HashSet<tb_BOOKINGS>();
            this.tb_CHECKINS = new HashSet<tb_CHECKINS>();
        }
    
        public int SEAT_ID { get; set; }
        public Nullable<int> AIRCRAFT_ID { get; set; }
        public string SEAT_NUMBER { get; set; }
        public string CLASS { get; set; }
    
        public virtual tb_AIRCRAFT tb_AIRCRAFT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BOOKINGS> tb_BOOKINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHECKINS> tb_CHECKINS { get; set; }
    }
}
