//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TAIKHOANNHANVIEN
    {
        public string IDTAIKHOAN { get; set; }
        public string IDNV { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
    }
}
